site_name: MySQL Kata
site_url: https://abhishekmalvadkar.github.io/mysql-kata
repo_url: https://github.com/abhishekmalvadkar/mysql-kata
nav:
  - Home: index.md
  - Katas:
      - Customer Orders Overview:
          - Problem: katas/customer-orders-overview/problem.md
          - Test Data: katas/customer-orders-overview/test-data.md
          - Solution: katas/customer-orders-overview/solution.md
          - Lesson Learned: katas/customer-orders-overview/lesson-learned.md
  - Misc:
      - Active User:
         - Problem with solution: active-user.md
      

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: light blue

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - pymdownx.extra
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
